version: '3'
services:
  web:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/alog_release?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r!!
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - NOTICE_SERVICE_URL=
      - AGGREGATOR_SERVICE_URL=
    ports:
      - "8085:8085"
    depends_on:
      "db":
        condition: service_healthy
      "redis":
        condition: service_healthy
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=alog_release
      - MYSQL_ROOT_PASSWORD=1q2w3e4r!!
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 10
  redis:
    image: redis:latest
    environment:
      - REDIS_MAXMEMORY=256mb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
  
